version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: chk
      MYSQL_PASSWORD: chk
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
